POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJuYW1lMSIsImlkIjoiNjJmNTIyMDc4MzNmMzA1ZTMzNTU0YWFmIiwiaWF0IjoxNjYwNTY4NzU4LCJleHAiOjE2NjA1NzIzNTh9.uEY0eJRRhwJKq4oyEMnzQsXbhf6mL4Dsm_tV8fzyvrY

{
    "title": "new",
    "author": "new",
    "url": "new",
    "likes": 1111
}