POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJuYW1lIiwiaWQiOiI2MmY1MjIwMTgzM2YzMDVlMzM1NTRhYWMiLCJpYXQiOjE2NjAyOTM4NTYsImV4cCI6MTY2MDI5NzQ1Nn0.KK7HKpLz1hQcyhSi3roNDIcy0Xz5HRTiYwk2Np6CFlQ

{
    "title": "title5",
    "author": "author5",
    "url": "url5",
    "likes": 5
}